version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd react-project && npm run build" #コンテナを立ち上げたときに自動的にbuildする
 
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend/react-project/build:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf